This notebook is developed using AndrewNg's course on coursera.

The inputs are taken as follows:

x-->x is a column vector of order 'n'x'm', where n=no. of features and m=training examples

y-->y is again a column vector of order 1xm

theta-->column vector of order 'n'x1
alpha--> it is the learning rate
m-->no. of training examples

In [60]:
import numpy as np
import pandas as pd

In [61]:
def gradient_descent(x,y,theta,alpha,iterations):
    m=y.size
    x=norm(x)
    for i in range(iterations):
        predictions=np.dot(theta.T,x)
        error=predictions-y
        theta=theta-(alpha*(1/m)*np.dot(x,error.T))
    return theta

In [62]:
def normal(x,y):
    x=x.T
    return np.dot(np.dot(np.linalg.pinv(np.dot(x.T,x)),x.T),y)

In [63]:
def norm(x):
    return (x-x.mean())/x.std()

In [64]:
x=np.array([2,3,2,1,1,3,4,5]).reshape(2,4)

In [65]:
x=np.insert(x,0,1,axis=0)
x

array([[1, 1, 1, 1],
       [2, 3, 2, 1],
       [1, 3, 4, 5]])

In [66]:
theta=np.random.randint(1,20,3).reshape(3,1)
theta

array([[7],
       [5],
       [3]])

In [67]:
y=np.array([5,8,5,1])

In [68]:
theta=gradient_descent(x,y,theta,0.01,1000)

In [69]:
np.dot(theta.T,x)

array([[  4.81447215,  10.40457487,   5.40681857,   0.40906227]])

In [70]:
theta=normal(x,y)

In [71]:
np.dot(theta.T,x)

array([ 5.        ,  8.16666667,  4.66666667,  1.16666667])